### ISSUE TITLE
여기에 질문을 남겨서 죄송합니다

### ISSUE THREAD

**Issue by aria1155** [Apple6050/server-files#1]
여기에 질문을 남겨서 정말 죄송합니다.
다름이 아니라 각별님의 불편한 동거 플러그인을 적용시킬려고했는데 안되서요..
보니깐 다른 플러그인들을 서버에 넣고 소스코드도 뭐 어떻게 하더라구요..제가 플러그인은 처음이라 어떻게하는지도 모르고 파일에 넣을줄만 알아서..혹시 조금 알려주시거나 도와주실수있나요..
아니면...염치없지만..플러그인들을 정리해서...주실수있나요...

**Comment by Apple6050** [comment]
@aria1155 님 커뮤니티 첫 활동을 축하드립니다!
해당 플러그인 목록은 **내일 보내드리도록** 하 겠습니다.

**Comment by Apple6050** [comment]
[Kotlin](https://github.com/noonmaru/kotlin-plugin/releases/tag/1.4.10)
[Tap](https://github.com/noonmaru/tap/releases/tag/3.2.0)
[ProtocolLib](https://ci.dmulloy2.net/view/ProtocolLib/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar)
플러그인과 InvCaptive 플러그인을 넣어주시고 [PaperMC Bukkit](https://papermc.io/api/v1/paper/1.16.3/latest/download) 버킷에서 서버를 켜주세요. @aria1155

**Comment by Apple6050** [comment]
그리고 빌드는 Tap은 윈도우시면 ./gradlew.bat paperJar 리눅스시면 ./gradlew paperJar으로 빌드하시면 됩니다.
이제 이슈 닫겠습니다.
@aria1155
